/**
 * \file transceiver_features.h
 *
 * Created: 30/06/2024 18:15:05
 * Author: luisc
 *
 * \brief  API file of transceiver feature access as generated by Project Wizard
 *
 * Copyright (c) 2014 Atmel Corporation. All rights reserved.
 *
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 *    Atmel microcontroller product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 * \page license License
 * Copyright(c) 2014, Atmel Corporation All rights reserved.
 *
 * Licensed under Atmel's Limited License Agreement --> EULA.txt
 */


#ifndef TRANSCEIVER_FEATURES_H
#define TRANSCEIVER_FEATURES_H

#include "tfa.h"

/**
 * \page wl_tfa Quick Start Guide For Usage of Additional Transceiver Features
 * This is a quick start guide for the usage of api's for accessing additional transceiver features
 *
 * \section wl_tfa_sens Transceiver Sensor Data
 * This module can be used to get the transceiver sensor data and use it as required.
 * The get_bat_sensor_data() is available for all transceivers and gets the current battery voltage
 * The get_temp_sensor_data() is used for atmegarfr2 to get the current temperature value
 *
 * \section wl_tfa_cw Continuous Wave Transmission
 * This module provides api's for performing continuous wave transmission in either CW or PRBS mode which
 * is used for FCC and Prototype testing of the board .The start_continuous_tx() starts the trx in CW or PRBS mode in the current channel/page settings
 * which can be stopped by calling stop_continuous_tx()
 */
 
float get_bat_sensor_data(void);





/*Reverses a float variable*/
float reverse_float( const float float_val);

/* Converts milli Volt into Volt*/
float convert_mv_to_v(uint16_t float_val);

#endif